version: '3.4'

services:
  carbookingapi:
    environment:
      ConnectionStrings__DefaultConnection: Server=mssqldb,1433;Database=CarBooking;User Id=sa;Password=yourStrong(!)Password;
    image: danipalli/carbookingapi
    ports:
      - 5000:5000
    depends_on:
      - mssqldb
  mssqldb:
    image: 'mcr.microsoft.com/mssql/server'
    environment:
      SA_PASSWORD: 'yourStrong(!)Password'
      ACCEPT_EULA: 'Y'
    ports:
      - 1433:1433
